package generator

import (
	"bytes"
	"fmt"
	"path/filepath"
	"sort"
)

func render(model packageModel) ([]byte, error) {
	var output bytes.Buffer
	output.WriteString("// Code generated by ormgen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&output, "package %s\n\n", model.name)

	imports := make([]importModel, 0, len(model.imports)+1)
	imports = append(imports, importModel{alias: model.queryAlias, path: queryImportPath, explicit: true})
	for _, imported := range model.imports {
		imports = append(imports, imported)
	}
	sort.Slice(imports, func(i, j int) bool {
		if imports[i].path == imports[j].path {
			return imports[i].alias < imports[j].alias
		}
		return imports[i].path < imports[j].path
	})
	output.WriteString("import (\n")
	for _, imported := range imports {
		if imported.explicit || imported.alias != filepath.Base(imported.path) {
			fmt.Fprintf(&output, "\t%s %q\n", imported.alias, imported.path)
		} else {
			fmt.Fprintf(&output, "\t%q\n", imported.path)
		}
	}
	output.WriteString(")\n\n")

	for _, entity := range model.entities {
		renderEntity(&output, model.queryAlias, entity)
	}
	return output.Bytes(), nil
}

func renderEntity(output *bytes.Buffer, queryAlias string, entity entityModel) {
	fmt.Fprintf(output, "type %sORMMetadata struct {\n", entity.name)
	fmt.Fprintf(output, "\tTable *%s.Table[%s]\n\n", queryAlias, entity.name)
	for _, field := range entity.fields {
		fmt.Fprintf(output, "\t%s %s.Column[%s, %s]\n", field.name, queryAlias, entity.name, field.typeText)
	}
	output.WriteString("}\n\n")
	fmt.Fprintf(output, "var %sORM = new%sORMMetadata()\n\n", entity.name, entity.name)
	fmt.Fprintf(output, "func new%sORMMetadata() %sORMMetadata {\n", entity.name, entity.name)
	fmt.Fprintf(output, "\ttable := must%sORMTable(%s.NewTable[%s](%q, []string{", entity.name, queryAlias, entity.name, entity.tableName)
	for index, field := range entity.fields {
		if index > 0 {
			output.WriteString(", ")
		}
		fmt.Fprintf(output, "%q", field.columnName)
	}
	fmt.Fprintf(output, "}, scan%sORM))\n", entity.name)
	fmt.Fprintf(output, "\treturn %sORMMetadata{\n", entity.name)
	output.WriteString("\t\tTable: table,\n")
	for _, field := range entity.fields {
		option := ""
		switch field.capability {
		case "readOnly":
			option = ", " + queryAlias + ".ReadOnlyColumn()"
		case "insertOnly":
			option = ", " + queryAlias + ".InsertOnlyColumn()"
		case "updateOnly":
			option = ", " + queryAlias + ".UpdateOnlyColumn()"
		}
		fmt.Fprintf(output, "\t\t%s: must%sORMColumn(%s.NewColumn[%s, %s](table, %q%s)),\n", field.name, entity.name, queryAlias, entity.name, field.typeText, field.columnName, option)
	}
	output.WriteString("\t}\n}\n\n")

	fmt.Fprintf(output, "func must%sORMTable(value *%s.Table[%s], err error) *%s.Table[%s] {\n", entity.name, queryAlias, entity.name, queryAlias, entity.name)
	fmt.Fprintf(output, "\tif err != nil { panic(%q + err.Error()) }\n", "ormgen: generated "+entity.name+" table metadata: ")
	output.WriteString("\treturn value\n}\n\n")

	fmt.Fprintf(output, "func must%sORMColumn[V any](value %s.Column[%s, V], err error) %s.Column[%s, V] {\n", entity.name, queryAlias, entity.name, queryAlias, entity.name)
	fmt.Fprintf(output, "\tif err != nil { panic(%q + err.Error()) }\n", "ormgen: generated "+entity.name+" column metadata: ")
	output.WriteString("\treturn value\n}\n\n")

	fmt.Fprintf(output, "func scan%sORM(row %s.RowScanner) (%s, error) {\n", entity.name, queryAlias, entity.name)
	fmt.Fprintf(output, "\tvar value %s\n", entity.name)
	output.WriteString("\terr := row.Scan(")
	for index, field := range entity.fields {
		if index > 0 {
			output.WriteString(", ")
		}
		fmt.Fprintf(output, "&value.%s", field.name)
	}
	output.WriteString(")\n\treturn value, err\n}\n\n")
}
