package apicheck

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/build"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const header = "# Sevlumen ORM public API surface v1\n# Generated by: go run ./cmd/apicheck -write -baseline api/v1.txt\n\n"

// Generate returns a deterministic, source-level manifest of exported Go API.
func Generate(root string) ([]byte, error) {
	absolute, err := filepath.Abs(root)
	if err != nil {
		return nil, fmt.Errorf("apicheck: resolve root: %w", err)
	}
	modulePath, err := readModulePath(filepath.Join(absolute, "go.mod"))
	if err != nil {
		return nil, err
	}

	var packages []packageSurface
	err = filepath.WalkDir(absolute, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if !entry.IsDir() {
			return nil
		}
		relative, err := filepath.Rel(absolute, path)
		if err != nil {
			return err
		}
		if relative != "." && skipDirectory(relative) {
			return filepath.SkipDir
		}
		value, ok, err := scanPackage(path, relative, modulePath)
		if err != nil {
			return err
		}
		if ok {
			packages = append(packages, value)
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("apicheck: scan packages: %w", err)
	}
	sort.Slice(packages, func(i, j int) bool { return packages[i].Path < packages[j].Path })

	var output bytes.Buffer
	output.WriteString(header)
	for _, pkg := range packages {
		fmt.Fprintf(&output, "package %s\n\n", pkg.Path)
		for _, declaration := range pkg.Declarations {
			output.WriteString(declaration)
			if !strings.HasSuffix(declaration, "\n") {
				output.WriteByte('\n')
			}
			output.WriteByte('\n')
		}
	}
	return output.Bytes(), nil
}

type packageSurface struct {
	Path         string
	Declarations []string
}

func scanPackage(directory, relative, modulePath string) (packageSurface, bool, error) {
	entries, err := os.ReadDir(directory)
	if err != nil {
		return packageSurface{}, false, err
	}
	fileSet := token.NewFileSet()
	var files []*ast.File
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		matches, err := build.Default.MatchFile(directory, name)
		if err != nil {
			return packageSurface{}, false, fmt.Errorf("match %s: %w", filepath.Join(relative, name), err)
		}
		if !matches {
			continue
		}
		file, err := parser.ParseFile(fileSet, filepath.Join(directory, name), nil, parser.SkipObjectResolution)
		if err != nil {
			return packageSurface{}, false, fmt.Errorf("parse %s: %w", filepath.Join(relative, name), err)
		}
		if file.Name.Name == "main" {
			continue
		}
		if !ast.FileExports(file) {
			continue
		}
		files = append(files, file)
	}
	if len(files) == 0 {
		return packageSurface{}, false, nil
	}

	var declarations []string
	for _, file := range files {
		for _, declaration := range file.Decls {
			switch value := declaration.(type) {
			case *ast.GenDecl:
				if value.Tok == token.IMPORT || len(value.Specs) == 0 {
					continue
				}
				value.Doc = nil
				stripSpecComments(value.Specs)
			case *ast.FuncDecl:
				value.Doc = nil
				value.Body = nil
			default:
				continue
			}
			rendered, err := render(fileSet, declaration)
			if err != nil {
				return packageSurface{}, false, fmt.Errorf("render %s: %w", relative, err)
			}
			declarations = append(declarations, rendered)
		}
	}
	if len(declarations) == 0 {
		return packageSurface{}, false, nil
	}
	sort.Strings(declarations)
	importPath := modulePath
	if relative != "." {
		importPath += "/" + filepath.ToSlash(relative)
	}
	return packageSurface{Path: importPath, Declarations: declarations}, true, nil
}

func stripSpecComments(specs []ast.Spec) {
	for _, spec := range specs {
		switch value := spec.(type) {
		case *ast.TypeSpec:
			value.Doc = nil
			value.Comment = nil
			stripTypeComments(value.Type)
		case *ast.ValueSpec:
			value.Doc = nil
			value.Comment = nil
		}
	}
}

func stripTypeComments(expression ast.Expr) {
	switch value := expression.(type) {
	case *ast.StructType:
		for _, field := range value.Fields.List {
			field.Doc = nil
			field.Comment = nil
		}
	case *ast.InterfaceType:
		for _, field := range value.Methods.List {
			field.Doc = nil
			field.Comment = nil
		}
	}
}

func render(fileSet *token.FileSet, node ast.Node) (string, error) {
	var buffer bytes.Buffer
	if err := format.Node(&buffer, fileSet, node); err != nil {
		return "", err
	}
	return strings.TrimSpace(buffer.String()) + "\n", nil
}

func skipDirectory(relative string) bool {
	parts := strings.Split(filepath.ToSlash(relative), "/")
	for _, part := range parts {
		switch part {
		case ".git", "vendor", "internal", "cmd", "docs", "api", "examples", "testdata":
			return true
		}
		if strings.HasPrefix(part, ".") {
			return true
		}
	}
	return false
}

func readModulePath(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("apicheck: read go.mod: %w", err)
	}
	for _, line := range strings.Split(string(data), "\n") {
		fields := strings.Fields(line)
		if len(fields) == 2 && fields[0] == "module" {
			return fields[1], nil
		}
	}
	return "", fmt.Errorf("apicheck: go.mod has no module directive")
}
