// Code generated by ormgen. DO NOT EDIT.

package rcapp

import (
	query "github.com/sevlumen/orm/postgres/query"
)

type AccountORMMetadata struct {
	Table *query.Table[Account]

	ID          query.Column[Account, int64]
	LoginEmail  query.Column[Account, string]
	LegacyNote  query.Column[Account, *string]
	DisplayName query.Column[Account, *string]
	Active      query.Column[Account, bool]
}

var AccountORM = newAccountORMMetadata()

func newAccountORMMetadata() AccountORMMetadata {
	table := mustAccountORMTable(query.NewTable[Account]("accounts", []string{"id", "login_email", "legacy_note", "display_name", "active"}, scanAccountORM))
	return AccountORMMetadata{
		Table:       table,
		ID:          mustAccountORMColumn(query.NewColumn[Account, int64](table, "id", query.InsertOnlyColumn())),
		LoginEmail:  mustAccountORMColumn(query.NewColumn[Account, string](table, "login_email")),
		LegacyNote:  mustAccountORMColumn(query.NewColumn[Account, *string](table, "legacy_note")),
		DisplayName: mustAccountORMColumn(query.NewColumn[Account, *string](table, "display_name")),
		Active:      mustAccountORMColumn(query.NewColumn[Account, bool](table, "active")),
	}
}

func mustAccountORMTable(value *query.Table[Account], err error) *query.Table[Account] {
	if err != nil {
		panic("ormgen: generated Account table metadata: " + err.Error())
	}
	return value
}

func mustAccountORMColumn[V any](value query.Column[Account, V], err error) query.Column[Account, V] {
	if err != nil {
		panic("ormgen: generated Account column metadata: " + err.Error())
	}
	return value
}

func scanAccountORM(row query.RowScanner) (Account, error) {
	var value Account
	err := row.Scan(&value.ID, &value.LoginEmail, &value.LegacyNote, &value.DisplayName, &value.Active)
	return value, err
}

type OrderORMMetadata struct {
	Table *query.Table[Order]

	ID        query.Column[Order, int64]
	AccountID query.Column[Order, int64]
	Total     query.Column[Order, int64]
	Status    query.Column[Order, string]
}

var OrderORM = newOrderORMMetadata()

func newOrderORMMetadata() OrderORMMetadata {
	table := mustOrderORMTable(query.NewTable[Order]("orders", []string{"id", "account_id", "total", "status"}, scanOrderORM))
	return OrderORMMetadata{
		Table:     table,
		ID:        mustOrderORMColumn(query.NewColumn[Order, int64](table, "id", query.InsertOnlyColumn())),
		AccountID: mustOrderORMColumn(query.NewColumn[Order, int64](table, "account_id")),
		Total:     mustOrderORMColumn(query.NewColumn[Order, int64](table, "total")),
		Status:    mustOrderORMColumn(query.NewColumn[Order, string](table, "status")),
	}
}

func mustOrderORMTable(value *query.Table[Order], err error) *query.Table[Order] {
	if err != nil {
		panic("ormgen: generated Order table metadata: " + err.Error())
	}
	return value
}

func mustOrderORMColumn[V any](value query.Column[Order, V], err error) query.Column[Order, V] {
	if err != nil {
		panic("ormgen: generated Order column metadata: " + err.Error())
	}
	return value
}

func scanOrderORM(row query.RowScanner) (Order, error) {
	var value Order
	err := row.Scan(&value.ID, &value.AccountID, &value.Total, &value.Status)
	return value, err
}
