// Code generated by ormgen. DO NOT EDIT.

package rcapp

import (
	ormquery "github.com/sevlumen/orm/postgres/query"
)

type AccountORMMetadata struct {
	Table *ormquery.Table[Account]

	ID          ormquery.Column[Account, int64]
	LoginEmail  ormquery.Column[Account, string]
	LegacyNote  ormquery.Column[Account, *string]
	DisplayName ormquery.Column[Account, *string]
	Active      ormquery.Column[Account, bool]
}

var AccountORM = newAccountORMMetadata()

func newAccountORMMetadata() AccountORMMetadata {
	table := mustAccountORMTable(ormquery.NewTable[Account]("accounts", []string{"id", "login_email", "legacy_note", "display_name", "active"}, scanAccountORM))
	return AccountORMMetadata{
		Table:       table,
		ID:          mustAccountORMColumn(ormquery.NewColumn[Account, int64](table, "id", ormquery.InsertOnlyColumn())),
		LoginEmail:  mustAccountORMColumn(ormquery.NewColumn[Account, string](table, "login_email")),
		LegacyNote:  mustAccountORMColumn(ormquery.NewColumn[Account, *string](table, "legacy_note")),
		DisplayName: mustAccountORMColumn(ormquery.NewColumn[Account, *string](table, "display_name")),
		Active:      mustAccountORMColumn(ormquery.NewColumn[Account, bool](table, "active")),
	}
}

func mustAccountORMTable(value *ormquery.Table[Account], err error) *ormquery.Table[Account] {
	if err != nil {
		panic("ormgen: generated Account table metadata: " + err.Error())
	}
	return value
}

func mustAccountORMColumn[V any](value ormquery.Column[Account, V], err error) ormquery.Column[Account, V] {
	if err != nil {
		panic("ormgen: generated Account column metadata: " + err.Error())
	}
	return value
}

func scanAccountORM(row ormquery.RowScanner) (Account, error) {
	var value Account
	err := row.Scan(&value.ID, &value.LoginEmail, &value.LegacyNote, &value.DisplayName, &value.Active)
	return value, err
}

type OrderORMMetadata struct {
	Table *ormquery.Table[Order]

	ID        ormquery.Column[Order, int64]
	AccountID ormquery.Column[Order, int64]
	Total     ormquery.Column[Order, int64]
	Status    ormquery.Column[Order, string]
}

var OrderORM = newOrderORMMetadata()

func newOrderORMMetadata() OrderORMMetadata {
	table := mustOrderORMTable(ormquery.NewTable[Order]("orders", []string{"id", "account_id", "total", "status"}, scanOrderORM))
	return OrderORMMetadata{
		Table:     table,
		ID:        mustOrderORMColumn(ormquery.NewColumn[Order, int64](table, "id", ormquery.InsertOnlyColumn())),
		AccountID: mustOrderORMColumn(ormquery.NewColumn[Order, int64](table, "account_id")),
		Total:     mustOrderORMColumn(ormquery.NewColumn[Order, int64](table, "total")),
		Status:    mustOrderORMColumn(ormquery.NewColumn[Order, string](table, "status")),
	}
}

func mustOrderORMTable(value *ormquery.Table[Order], err error) *ormquery.Table[Order] {
	if err != nil {
		panic("ormgen: generated Order table metadata: " + err.Error())
	}
	return value
}

func mustOrderORMColumn[V any](value ormquery.Column[Order, V], err error) ormquery.Column[Order, V] {
	if err != nil {
		panic("ormgen: generated Order column metadata: " + err.Error())
	}
	return value
}

func scanOrderORM(row ormquery.RowScanner) (Order, error) {
	var value Order
	err := row.Scan(&value.ID, &value.AccountID, &value.Total, &value.Status)
	return value, err
}
